[package]
name = "blip_buf-rs"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/nomyfan/blip_buf-rs"
license-file = "LICENSE"
description = "A Rust port of blip_buf, a small waveform synthesis library meant for use in classic video game sound chip emulation."
